export const PERMISSIONS = {
  RESIDENT_VIEW: "RESIDENT:VIEW",
  RESIDENT_SENSITIVE_VIEW: "RESIDENT_SENSITIVE:VIEW",
  SCREENING_VIEW: "SCREENING:VIEW",
  ASSESSMENT_VIEW: "ASSESSMENT:VIEW",
  ADMISSION_VIEW: "ADMISSION:VIEW",
  FACILITY_VIEW: "FACILITY:VIEW",
  CARE_PLAN_VIEW: "CARE_PLAN:VIEW",
  CARE_TASK_VIEW: "CARE_TASK:VIEW",
  AUDIT_LOG_VIEW: "AUDIT_LOG:VIEW",
  PHI_ACCESS_LOG_VIEW: "PHI_ACCESS_LOG:VIEW",
  NOTIFICATION_VIEW: "NOTIFICATION:VIEW",
  ROLE_VIEW: "ROLE:VIEW",
  PERMISSION_VIEW: "PERMISSION:VIEW",
  USER_VIEW: "USER:VIEW",
  CARE_LEVEL_VIEW: "CARE_LEVEL:VIEW",
  ASSESSMENT_METRIC_VIEW: "ASSESSMENT_METRIC:VIEW",
  INVENTORY_VIEW: "INVENTORY:VIEW",
  STAFFING_RATIO_VIEW: "STAFFING_RATIO:VIEW",
  DEMO_DATA_VIEW: "DEMO_DATA:VIEW",
  DEMO_DATA_SEED: "DEMO_DATA:SEED",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
