### Get all SLA Configs -> 200 OK
GET http://localhost:8080/admin/sla-configs

###

### Create SLA Config -> 201 Created
POST http://localhost:8080/admin/sla-configs
Content-Type: application/json

{
    "severity_id": 1,
    "sla_window_hrs": 24
}

###

### Update SLA Config -> 200 OK
PUT http://localhost:8080/admin/sla-configs/1
Content-Type: application/json

{
    "severity_id": 2,
    "sla_window_hrs": 48
}

### Validation Test for SLA Config -> 400 Bad Request
POST http://localhost:8080/admin/sla-configs
Content-Type: application/json

{
    "severity_id": null,
    "sla_window_hrs": null
}

### Update Non-existing SLA -> 404 Not Found
PUT http://localhost:8080/admin/sla-configs/999
Content-Type: application/json

{
    "severity_id": 1,
    "sla_window_hrs": 24
}